"""
config/pre_league.py

PREVIEW FILE - Leagues fetched from API-Football for manual verification.
This file should be checked to ensure all IDs correspond to correct leagues.
Only copy verified leagues to config/leagues.py for actual use.

Regenerated: 2026-04-16T08:23:30.022707
"""

API_LEAGUES = {
    1: {"name": "World Cup", "country": "World"},
    2: {"name": "UEFA Champions League", "country": "World"},
    3: {"name": "UEFA Europa League", "country": "World"},
    4: {"name": "Euro Championship", "country": "World"},
    5: {"name": "UEFA Nations League", "country": "World"},
    6: {"name": "Africa Cup of Nations", "country": "World"},
    7: {"name": "Asian Cup", "country": "World"},
    8: {"name": "World Cup - Women", "country": "World"},
    9: {"name": "Copa America", "country": "World"},
    10: {"name": "Friendlies", "country": "World"},
    11: {"name": "CONMEBOL Sudamericana", "country": "World"},
    12: {"name": "CAF Champions League", "country": "World"},
    13: {"name": "CONMEBOL Libertadores", "country": "World"},
    14: {"name": "UEFA Youth League", "country": "World"},
    15: {"name": "FIFA Club World Cup", "country": "World"},
    16: {"name": "CONCACAF Champions League", "country": "World"},
    17: {"name": "AFC Champions League Elite", "country": "World"},
    18: {"name": "AFC Champions League Two", "country": "World"},
    19: {"name": "African Nations Championship", "country": "World"},
    20: {"name": "CAF Confederation Cup", "country": "World"},
    21: {"name": "Confederations Cup", "country": "World"},
    22: {"name": "CONCACAF Gold Cup", "country": "World"},
    23: {"name": "EAFF E-1 Football Championship", "country": "World"},
    24: {"name": "ASEAN Championship", "country": "World"},
    25: {"name": "Gulf Cup of Nations", "country": "World"},
    26: {"name": "International Champions Cup", "country": "World"},
    27: {"name": "OFC Champions League", "country": "World"},
    28: {"name": "SAFF Championship", "country": "World"},
    29: {"name": "World Cup - Qualification Africa", "country": "World"},
    30: {"name": "World Cup - Qualification Asia", "country": "World"},
    31: {"name": "World Cup - Qualification CONCACAF", "country": "World"},
    32: {"name": "World Cup - Qualification Europe", "country": "World"},
    33: {"name": "World Cup - Qualification Oceania", "country": "World"},
    34: {"name": "World Cup - Qualification South America", "country": "World"},
    35: {"name": "Asian Cup - Qualification", "country": "World"},
    36: {"name": "Africa Cup of Nations - Qualification", "country": "World"},
    37: {"name": "World Cup - Qualification Intercontinental Play-offs", "country": "World"},
    38: {"name": "UEFA U21 Championship", "country": "World"},
    39: {"name": "Premier League", "country": "England"},
    40: {"name": "Championship", "country": "England"},
    41: {"name": "League One", "country": "England"},
    42: {"name": "League Two", "country": "England"},
    43: {"name": "National League", "country": "England"},
    44: {"name": "FA WSL", "country": "England"},
    45: {"name": "FA Cup", "country": "England"},
    46: {"name": "EFL Trophy", "country": "England"},
    47: {"name": "FA Trophy", "country": "England"},
    48: {"name": "League Cup", "country": "England"},
    49: {"name": "National League - Play-offs", "country": "England"},
    50: {"name": "National League - North", "country": "England"},
    51: {"name": "National League - South", "country": "England"},
    52: {"name": "Non League Div One - Isthmian North", "country": "England"},
    53: {"name": "Non League Div One - Isthmian South Central", "country": "England"},
    54: {"name": "Non League Div One - Northern West", "country": "England"},
    55: {"name": "Non League Div One - Northern Midlands", "country": "England"},
    56: {"name": "Non League Div One - Southern South", "country": "England"},
    57: {"name": "Non League Div One - Isthmian South East", "country": "England"},
    58: {"name": "Non League Premier - Isthmian", "country": "England"},
    59: {"name": "Non League Premier - Northern", "country": "England"},
    60: {"name": "Non League Premier - Southern South", "country": "England"},
    61: {"name": "Ligue 1", "country": "France"},
    62: {"name": "Ligue 2", "country": "France"},
    63: {"name": "National 1", "country": "France"},
    64: {"name": "Feminine Division 1", "country": "France"},
    65: {"name": "Coupe de la Ligue", "country": "France"},
    66: {"name": "Coupe de France", "country": "France"},
    67: {"name": "National 2 - Group A", "country": "France"},
    68: {"name": "National 2 - Group B", "country": "France"},
    69: {"name": "National 2 - Group C", "country": "France"},
    70: {"name": "National 2 - Group D", "country": "France"},
    71: {"name": "Serie A", "country": "Brazil"},
    72: {"name": "Serie B", "country": "Brazil"},
    73: {"name": "Copa Do Brasil", "country": "Brazil"},
    74: {"name": "Brasileiro Women", "country": "Brazil"},
    75: {"name": "Serie C", "country": "Brazil"},
    76: {"name": "Serie D", "country": "Brazil"},
    77: {"name": "Alagoano", "country": "Brazil"},
    78: {"name": "Bundesliga", "country": "Germany"},
    79: {"name": "2. Bundesliga", "country": "Germany"},
    80: {"name": "3. Liga", "country": "Germany"},
    81: {"name": "DFB Pokal", "country": "Germany"},
    82: {"name": "Frauen Bundesliga", "country": "Germany"},
    83: {"name": "Regionalliga - Bayern", "country": "Germany"},
    84: {"name": "Regionalliga - Nord", "country": "Germany"},
    85: {"name": "Regionalliga - Nordost", "country": "Germany"},
    86: {"name": "Regionalliga - SudWest", "country": "Germany"},
    87: {"name": "Regionalliga - West", "country": "Germany"},
    88: {"name": "Eredivisie", "country": "Netherlands"},
    89: {"name": "Eerste Divisie", "country": "Netherlands"},
    90: {"name": "KNVB Beker", "country": "Netherlands"},
    91: {"name": "Eredivisie Women", "country": "Netherlands"},
    92: {"name": "Derde Divisie - Saturday", "country": "Netherlands"},
    93: {"name": "Derde Divisie - Sunday", "country": "Netherlands"},
    94: {"name": "Primeira Liga", "country": "Portugal"},
    95: {"name": "Segunda Liga", "country": "Portugal"},
    96: {"name": "Taça de Portugal", "country": "Portugal"},
    97: {"name": "Taça da Liga", "country": "Portugal"},
    98: {"name": "J1 League", "country": "Japan"},
    99: {"name": "J2/J3 League", "country": "Japan"},
    100: {"name": "J3 League", "country": "Japan"},
    101: {"name": "J-League Cup", "country": "Japan"},
    102: {"name": "Emperor Cup", "country": "Japan"},
    103: {"name": "Eliteserien", "country": "Norway"},
    104: {"name": "1. Division", "country": "Norway"},
    105: {"name": "NM Cupen", "country": "Norway"},
    106: {"name": "Ekstraklasa", "country": "Poland"},
    107: {"name": "I Liga", "country": "Poland"},
    108: {"name": "Cup", "country": "Poland"},
    109: {"name": "II Liga - East", "country": "Poland"},
    110: {"name": "Premier League", "country": "Wales"},
    111: {"name": "FAW Championship", "country": "Wales"},
    112: {"name": "Welsh Cup", "country": "Wales"},
    113: {"name": "Allsvenskan", "country": "Sweden"},
    114: {"name": "Superettan", "country": "Sweden"},
    115: {"name": "Svenska Cupen", "country": "Sweden"},
    116: {"name": "Premier League", "country": "Belarus"},
    117: {"name": "1. Division", "country": "Belarus"},
    118: {"name": "2. Division", "country": "Belarus"},
    119: {"name": "Superliga", "country": "Denmark"},
    120: {"name": "1. Division", "country": "Denmark"},
    121: {"name": "DBU Pokalen", "country": "Denmark"},
    122: {"name": "2. Division", "country": "Denmark"},
    123: {"name": "2nd Division - Group 2", "country": "Denmark"},
    124: {"name": "Denmark Series - Group 1", "country": "Denmark"},
    125: {"name": "Denmark Series - Group 2", "country": "Denmark"},
    126: {"name": "Denmark Series - Group 3", "country": "Denmark"},
    127: {"name": "Denmark Series - Group 4", "country": "Denmark"},
    128: {"name": "Liga Profesional Argentina", "country": "Argentina"},
    129: {"name": "Primera Nacional", "country": "Argentina"},
    130: {"name": "Copa Argentina", "country": "Argentina"},
    131: {"name": "Primera B Metropolitana", "country": "Argentina"},
    132: {"name": "Primera C", "country": "Argentina"},
    133: {"name": "Primera D", "country": "Argentina"},
    134: {"name": "Torneo Federal A", "country": "Argentina"},
    135: {"name": "Serie A", "country": "Italy"},
    136: {"name": "Serie B", "country": "Italy"},
    137: {"name": "Coppa Italia", "country": "Italy"},
    138: {"name": "Serie C - Girone A", "country": "Italy"},
    139: {"name": "Serie A Women", "country": "Italy"},
    140: {"name": "La Liga", "country": "Spain"},
    141: {"name": "Segunda División", "country": "Spain"},
    142: {"name": "Primera División Femenina", "country": "Spain"},
    143: {"name": "Copa del Rey", "country": "Spain"},
    144: {"name": "Jupiler Pro League", "country": "Belgium"},
    145: {"name": "Challenger Pro League", "country": "Belgium"},
    146: {"name": "Super League Women", "country": "Belgium"},
    147: {"name": "Cup", "country": "Belgium"},
    148: {"name": "Second Amateur Division - ACFF", "country": "Belgium"},
    149: {"name": "Second Amateur Division - VFV A", "country": "Belgium"},
    150: {"name": "Second Amateur Division - VFV B", "country": "Belgium"},
    151: {"name": "Third Amateur Division - VFV A", "country": "Belgium"},
    152: {"name": "Third Amateur Division - VFV B", "country": "Belgium"},
    153: {"name": "Provincial - Antwerpen", "country": "Belgium"},
    154: {"name": "Provincial - Brabant VFV", "country": "Belgium"},
    155: {"name": "Provincial - Hainaut", "country": "Belgium"},
    156: {"name": "Provincial - Liege", "country": "Belgium"},
    157: {"name": "Provincial - Limburg", "country": "Belgium"},
    158: {"name": "Provincial - Luxembourg", "country": "Belgium"},
    159: {"name": "Provincial - Namur", "country": "Belgium"},
    160: {"name": "Provincial - Oost-Vlaanderen", "country": "Belgium"},
    161: {"name": "Provincial - West-Vlaanderen", "country": "Belgium"},
    162: {"name": "Primera División", "country": "Costa-Rica"},
    163: {"name": "Liga de Ascenso", "country": "Costa-Rica"},
    164: {"name": "Úrvalsdeild", "country": "Iceland"},
    165: {"name": "1. Deild", "country": "Iceland"},
    166: {"name": "2. Deild", "country": "Iceland"},
    167: {"name": "Cup", "country": "Iceland"},
    168: {"name": "League Cup", "country": "Iceland"},
    169: {"name": "Super League", "country": "China"},
    170: {"name": "League One", "country": "China"},
    171: {"name": "FA Cup", "country": "China"},
    172: {"name": "First League", "country": "Bulgaria"},
    173: {"name": "Second League", "country": "Bulgaria"},
    174: {"name": "Cup", "country": "Bulgaria"},
    175: {"name": "Third League - Northeast", "country": "Bulgaria"},
    176: {"name": "Third League - Northwest", "country": "Bulgaria"},
    177: {"name": "Third League - Southeast", "country": "Bulgaria"},
    178: {"name": "Third League - Southwest", "country": "Bulgaria"},
    179: {"name": "Premiership", "country": "Scotland"},
    180: {"name": "Championship", "country": "Scotland"},
    181: {"name": "FA Cup", "country": "Scotland"},
    182: {"name": "Challenge Cup", "country": "Scotland"},
    183: {"name": "League One", "country": "Scotland"},
    184: {"name": "League Two", "country": "Scotland"},
    185: {"name": "League Cup", "country": "Scotland"},
    186: {"name": "Ligue 1", "country": "Algeria"},
    187: {"name": "Ligue 2", "country": "Algeria"},
    188: {"name": "A-League", "country": "Australia"},
    189: {"name": "Capital Territory NPL", "country": "Australia"},
    190: {"name": "A-League Women", "country": "Australia"},
    191: {"name": "Brisbane Premier League", "country": "Australia"},
    192: {"name": "New South Wales NPL", "country": "Australia"},
    193: {"name": "Northern Territory Premier League", "country": "Australia"},
    194: {"name": "South Australia NPL", "country": "Australia"},
    195: {"name": "Victoria NPL", "country": "Australia"},
    196: {"name": "Western Australia NPL", "country": "Australia"},
    197: {"name": "Super League 1", "country": "Greece"},
    198: {"name": "Football League", "country": "Greece"},
    199: {"name": "Cup", "country": "Greece"},
    200: {"name": "Botola Pro", "country": "Morocco"},
    201: {"name": "Botola 2", "country": "Morocco"},
    202: {"name": "Ligue 1", "country": "Tunisia"},
    203: {"name": "Süper Lig", "country": "Turkey"},
    204: {"name": "1. Lig", "country": "Turkey"},
    205: {"name": "2. Lig", "country": "Turkey"},
    206: {"name": "Türkiye Kupası", "country": "Turkey"},
    207: {"name": "Super League", "country": "Switzerland"},
    208: {"name": "Challenge League", "country": "Switzerland"},
    209: {"name": "Schweizer Cup", "country": "Switzerland"},
    210: {"name": "HNL", "country": "Croatia"},
    211: {"name": "First NL", "country": "Croatia"},
    212: {"name": "Cup", "country": "Croatia"},
    213: {"name": "Third NL - Istok", "country": "Croatia"},
    214: {"name": "Third NL - Jug", "country": "Croatia"},
    215: {"name": "Third NL - Sjever", "country": "Croatia"},
    216: {"name": "Third NL - Sredite", "country": "Croatia"},
    217: {"name": "Third NL - Zapad", "country": "Croatia"},
    218: {"name": "Bundesliga", "country": "Austria"},
    219: {"name": "2. Liga", "country": "Austria"},
    220: {"name": "Cup", "country": "Austria"},
    221: {"name": "Regionalliga - Ost", "country": "Austria"},
    222: {"name": "Regionalliga - Mitte", "country": "Austria"},
    223: {"name": "Regionalliga - West", "country": "Austria"},
    224: {"name": "Landesliga - Burgenland", "country": "Austria"},
    225: {"name": "Landesliga - Karnten", "country": "Austria"},
    226: {"name": "Landesliga - Niederosterreich", "country": "Austria"},
    227: {"name": "Landesliga - Oberosterreich", "country": "Austria"},
    228: {"name": "Landesliga - Salzburg", "country": "Austria"},
    229: {"name": "Landesliga - Steiermark", "country": "Austria"},
    230: {"name": "Landesliga - Tirol", "country": "Austria"},
    231: {"name": "Landesliga - Vorarlbergliga", "country": "Austria"},
    232: {"name": "Landesliga - Wien", "country": "Austria"},
    233: {"name": "Premier League", "country": "Egypt"},
    234: {"name": "Liga Nacional", "country": "Honduras"},
    235: {"name": "Premier League", "country": "Russia"},
    236: {"name": "First League", "country": "Russia"},
    237: {"name": "Cup", "country": "Russia"},
    238: {"name": "Youth Championship", "country": "Russia"},
    239: {"name": "Primera A", "country": "Colombia"},
    240: {"name": "Primera B", "country": "Colombia"},
    241: {"name": "Copa Colombia", "country": "Colombia"},
    242: {"name": "Liga Pro", "country": "Ecuador"},
    243: {"name": "Liga Pro Serie B", "country": "Ecuador"},
    244: {"name": "Veikkausliiga", "country": "Finland"},
    245: {"name": "Ykkönen", "country": "Finland"},
    246: {"name": "Suomen Cup", "country": "Finland"},
    247: {"name": "Kakkonen - Lohko A", "country": "Finland"},
    248: {"name": "Kakkonen - Lohko B", "country": "Finland"},
    249: {"name": "Kakkonen - Lohko C", "country": "Finland"},
    250: {"name": "Division Profesional - Apertura", "country": "Paraguay"},
    251: {"name": "Division Intermedia", "country": "Paraguay"},
    252: {"name": "Division Profesional - Clausura", "country": "Paraguay"},
    253: {"name": "Major League Soccer", "country": "USA"},
    254: {"name": "NWSL Women", "country": "USA"},
    255: {"name": "USL Championship", "country": "USA"},
    256: {"name": "USL League Two", "country": "USA"},
    257: {"name": "US Open Cup", "country": "USA"},
    258: {"name": "Canadian Soccer League", "country": "Canada"},
    259: {"name": "Canadian Championship", "country": "Canada"},
    260: {"name": "Pacific Coast Soccer League", "country": "Canada"},
    261: {"name": "National Division", "country": "Luxembourg"},
    262: {"name": "Liga MX", "country": "Mexico"},
    263: {"name": "Liga de Expansión MX", "country": "Mexico"},
    264: {"name": "Copa MX", "country": "Mexico"},
    265: {"name": "Primera División", "country": "Chile"},
    266: {"name": "Primera B", "country": "Chile"},
    267: {"name": "Copa Chile", "country": "Chile"},
    268: {"name": "Primera División - Apertura", "country": "Uruguay"},
    269: {"name": "Segunda División", "country": "Uruguay"},
    270: {"name": "Primera División - Clausura", "country": "Uruguay"},
    271: {"name": "NB I", "country": "Hungary"},
    272: {"name": "NB II", "country": "Hungary"},
    273: {"name": "Magyar Kupa", "country": "Hungary"},
    274: {"name": "Liga 1", "country": "Indonesia"},
    275: {"name": "Liga 2", "country": "Indonesia"},
    276: {"name": "FKF Premier League", "country": "Kenya"},
    277: {"name": "Super League", "country": "Kenya"},
    278: {"name": "Super League", "country": "Malaysia"},
    279: {"name": "Premier League", "country": "Malaysia"},
    280: {"name": "Premiership", "country": "New-Zealand"},
    281: {"name": "Primera División", "country": "Peru"},
    282: {"name": "Segunda División", "country": "Peru"},
    283: {"name": "Liga I", "country": "Romania"},
    284: {"name": "Liga II", "country": "Romania"},
    285: {"name": "Cupa României", "country": "Romania"},
    286: {"name": "Super Liga", "country": "Serbia"},
    287: {"name": "Prva Liga", "country": "Serbia"},
    288: {"name": "Premier Soccer League", "country": "South-Africa"},
    289: {"name": "1st Division", "country": "South-Africa"},
    290: {"name": "Persian Gulf Pro League", "country": "Iran"},
    291: {"name": "Azadegan League", "country": "Iran"},
    292: {"name": "K League 1", "country": "South-Korea"},
    293: {"name": "K League 2", "country": "South-Korea"},
    294: {"name": "FA Cup", "country": "South-Korea"},
    295: {"name": "K3 League", "country": "South-Korea"},
    296: {"name": "Thai League 1", "country": "Thailand"},
    297: {"name": "Thai League 2", "country": "Thailand"},
    298: {"name": "FA Cup", "country": "Thailand"},
    299: {"name": "Primera División", "country": "Venezuela"},
    300: {"name": "Segunda División", "country": "Venezuela"},
    301: {"name": "Pro League", "country": "United-Arab-Emirates"},
    302: {"name": "League Cup", "country": "United-Arab-Emirates"},
    303: {"name": "Division 1", "country": "United-Arab-Emirates"},
    304: {"name": "Liga Panameña de Fútbol", "country": "Panama"},
    305: {"name": "Stars League", "country": "Qatar"},
    306: {"name": "Second Division", "country": "Qatar"},
    307: {"name": "Pro League", "country": "Saudi-Arabia"},
    308: {"name": "Division 1", "country": "Saudi-Arabia"},
    309: {"name": "Division 2", "country": "Saudi-Arabia"},
    310: {"name": "Superliga", "country": "Albania"},
    311: {"name": "1st Division", "country": "Albania"},
    312: {"name": "1a Divisió", "country": "Andorra"},
    313: {"name": "2a Divisió", "country": "Andorra"},
    314: {"name": "Cup", "country": "Bosnia"},
    315: {"name": "Premijer Liga", "country": "Bosnia"},
    316: {"name": "1st League - FBiH", "country": "Bosnia"},
    317: {"name": "1st League - RS", "country": "Bosnia"},
    318: {"name": "1. Division", "country": "Cyprus"},
    319: {"name": "2. Division", "country": "Cyprus"},
    320: {"name": "3. Division", "country": "Cyprus"},
    321: {"name": "Cup", "country": "Cyprus"},
    322: {"name": "Premier League", "country": "Jamaica"},
    323: {"name": "Indian Super League", "country": "India"},
    324: {"name": "I-League", "country": "India"},
    325: {"name": "Santosh Trophy", "country": "India"},
    326: {"name": "Erovnuli Liga 2", "country": "Georgia"},
    327: {"name": "Erovnuli Liga", "country": "Georgia"},
    328: {"name": "Esiliiga A", "country": "Estonia"},
    329: {"name": "Meistriliiga", "country": "Estonia"},
    330: {"name": "Premier League", "country": "Kuwait"},
    331: {"name": "Division 1", "country": "Kuwait"},
    332: {"name": "Super Liga", "country": "Slovakia"},
    333: {"name": "Premier League", "country": "Ukraine"},
    334: {"name": "Persha Liga", "country": "Ukraine"},
    335: {"name": "Cup", "country": "Ukraine"},
    336: {"name": "Druha Liga", "country": "Ukraine"},
    337: {"name": "Druha Liga - Group B", "country": "Ukraine"},
    338: {"name": "Primera Division", "country": "Guatemala"},
    339: {"name": "Liga Nacional", "country": "Guatemala"},
    340: {"name": "V.League 1", "country": "Vietnam"},
    341: {"name": "Cup", "country": "Vietnam"},
    342: {"name": "Premier League", "country": "Armenia"},
    343: {"name": "First League", "country": "Armenia"},
    344: {"name": "Primera División", "country": "Bolivia"},
    345: {"name": "Czech Liga", "country": "Czech-Republic"},
    346: {"name": "FNL", "country": "Czech-Republic"},
    347: {"name": "Cup", "country": "Czech-Republic"},
    348: {"name": "3. liga - CFL A", "country": "Czech-Republic"},
    349: {"name": "3. liga - MSFL", "country": "Czech-Republic"},
    350: {"name": "4. liga - Divizie A", "country": "Czech-Republic"},
    351: {"name": "4. liga - Divizie B", "country": "Czech-Republic"},
    352: {"name": "4. liga - Divizie C", "country": "Czech-Republic"},
    353: {"name": "4. liga - Divizie D", "country": "Czech-Republic"},
    354: {"name": "4. liga - Divizie E", "country": "Czech-Republic"},
    355: {"name": "First League", "country": "Montenegro"},
    356: {"name": "Second League", "country": "Montenegro"},
    357: {"name": "Premier Division", "country": "Ireland"},
    358: {"name": "First Division", "country": "Ireland"},
    359: {"name": "FAI Cup", "country": "Ireland"},
    360: {"name": "League Cup", "country": "Ireland"},
    361: {"name": "1 Lyga", "country": "Lithuania"},
    362: {"name": "A Lyga", "country": "Lithuania"},
    363: {"name": "Premier League", "country": "Ethiopia"},
    364: {"name": "1. Liga", "country": "Latvia"},
    365: {"name": "Virsliga", "country": "Latvia"},
    366: {"name": "1. Deild", "country": "Faroe-Islands"},
    367: {"name": "Meistaradeildin", "country": "Faroe-Islands"},
    368: {"name": "Premier League", "country": "Singapore"},
    369: {"name": "Super League", "country": "Uzbekistan"},
    370: {"name": "Primera Division", "country": "El-Salvador"},
    371: {"name": "First League", "country": "Macedonia"},
    372: {"name": "Second League", "country": "Macedonia"},
    373: {"name": "1. SNL", "country": "Slovenia"},
    374: {"name": "2. SNL", "country": "Slovenia"},
    375: {"name": "Cup", "country": "Slovenia"},
    376: {"name": "National Football League", "country": "Fiji"},
    377: {"name": "Division d'Honneur", "country": "Guadeloupe"},
    378: {"name": "Ligue 1", "country": "Guinea"},
    379: {"name": "Ligue Haïtienne", "country": "Haiti"},
    380: {"name": "Premier League", "country": "Hong-Kong"},
    381: {"name": "HKFA 1st Division", "country": "Hong-Kong"},
    382: {"name": "Liga Leumit", "country": "Israel"},
    383: {"name": "Ligat Ha'al", "country": "Israel"},
    384: {"name": "State Cup", "country": "Israel"},
    385: {"name": "Toto Cup Ligat Al", "country": "Israel"},
    386: {"name": "Ligue 1", "country": "Ivory-Coast"},
    387: {"name": "League", "country": "Jordan"},
    388: {"name": "1. Division", "country": "Kazakhstan"},
    389: {"name": "Premier League", "country": "Kazakhstan"},
    390: {"name": "Premier League", "country": "Lebanon"},
    391: {"name": "Super League", "country": "Malawi"},
    392: {"name": "Challenge League", "country": "Malta"},
    393: {"name": "Premier League", "country": "Malta"},
    394: {"name": "Super Liga", "country": "Moldova"},
    395: {"name": "Liga 1", "country": "Moldova"},
    396: {"name": "Primera Division", "country": "Nicaragua"},
    397: {"name": "Girabola", "country": "Angola"},
    398: {"name": "Premier League", "country": "Bangladesh"},
    399: {"name": "NPFL", "country": "Nigeria"},
    400: {"name": "Super League", "country": "Zambia"},
    401: {"name": "Premier Soccer League", "country": "Zimbabwe"},
    402: {"name": "Sudani Premier League", "country": "Sudan"},
    403: {"name": "Ligue 1", "country": "Senegal"},
    404: {"name": "Campionato", "country": "San-Marino"},
    405: {"name": "National Soccer League", "country": "Rwanda"},
    406: {"name": "Professional League", "country": "Oman"},
    407: {"name": "Championship", "country": "Northern-Ireland"},
    408: {"name": "Premiership", "country": "Northern-Ireland"},
    409: {"name": "Premier League", "country": "Namibia"},
    410: {"name": "C-League", "country": "Cambodia"},
    411: {"name": "Elite One", "country": "Cameroon"},
    412: {"name": "Premier League", "country": "Botswana"},
    413: {"name": "Super League", "country": "Bhutan"},
    414: {"name": "Premier League", "country": "Bermuda"},
    415: {"name": "Championnat National", "country": "Benin"},
    416: {"name": "Premier League", "country": "Belize"},
    417: {"name": "Premier League", "country": "Bahrain"},
    418: {"name": "Birinci Dasta", "country": "Azerbaijan"},
    419: {"name": "Premyer Liqa", "country": "Azerbaijan"},
    420: {"name": "Cup", "country": "Azerbaijan"},
    421: {"name": "Division di Honor", "country": "Aruba"},
    422: {"name": "Premier League", "country": "Barbados"},
    423: {"name": "Ligue 1", "country": "Burkina-Faso"},
    424: {"name": "Ligue 1", "country": "Congo-DR"},
    425: {"name": "Premier League", "country": "Syria"},
    426: {"name": "Serie D - Girone A", "country": "Italy"},
    427: {"name": "Serie D - Girone B", "country": "Italy"},
    428: {"name": "Serie D - Girone C", "country": "Italy"},
    429: {"name": "Serie D - Girone D", "country": "Italy"},
    430: {"name": "Serie D - Girone E", "country": "Italy"},
    431: {"name": "Serie D - Girone F", "country": "Italy"},
    432: {"name": "Serie D - Girone G", "country": "Italy"},
    433: {"name": "Serie D - Girone H", "country": "Italy"},
    434: {"name": "Serie D - Girone I", "country": "Italy"},
    435: {"name": "Primera División RFEF - Group 1", "country": "Spain"},
    436: {"name": "Primera División RFEF - Group 2", "country": "Spain"},
    437: {"name": "Primera División RFEF - Group 3", "country": "Spain"},
    438: {"name": "Primera División RFEF - Group 4", "country": "Spain"},
    439: {"name": "Tercera División RFEF - Group 1", "country": "Spain"},
    440: {"name": "Tercera División RFEF - Group 2", "country": "Spain"},
    441: {"name": "Tercera División RFEF - Group 3", "country": "Spain"},
    442: {"name": "Tercera División RFEF - Group 4", "country": "Spain"},
    443: {"name": "Tercera División RFEF - Group 5", "country": "Spain"},
    444: {"name": "Tercera División RFEF - Group 6", "country": "Spain"},
    445: {"name": "Tercera División RFEF - Group 7", "country": "Spain"},
    446: {"name": "Tercera División RFEF - Group 8", "country": "Spain"},
    447: {"name": "Tercera División RFEF - Group 9", "country": "Spain"},
    448: {"name": "Tercera División RFEF - Group 10", "country": "Spain"},
    449: {"name": "Tercera División RFEF - Group 11", "country": "Spain"},
    450: {"name": "Tercera División RFEF - Group 12", "country": "Spain"},
    451: {"name": "Tercera División RFEF - Group 13", "country": "Spain"},
    452: {"name": "Tercera División RFEF - Group 14", "country": "Spain"},
    453: {"name": "Tercera División RFEF - Group 15", "country": "Spain"},
    454: {"name": "Tercera División RFEF - Group 16", "country": "Spain"},
    455: {"name": "Tercera División RFEF - Group 17", "country": "Spain"},
    456: {"name": "Tercera División RFEF - Group 18", "country": "Spain"},
    457: {"name": "Campeonato de Portugal Prio - Group A", "country": "Portugal"},
    458: {"name": "Campeonato de Portugal Prio - Group B", "country": "Portugal"},
    459: {"name": "Campeonato de Portugal Prio - Group C", "country": "Portugal"},
    460: {"name": "Campeonato de Portugal Prio - Group D", "country": "Portugal"},
    461: {"name": "National 3 - Group A", "country": "France"},
    462: {"name": "National 3 - Group B", "country": "France"},
    463: {"name": "National 3 - Group C", "country": "France"},
    464: {"name": "National 3 - Group D", "country": "France"},
    465: {"name": "National 3 - Group E", "country": "France"},
    466: {"name": "National 3 - Group F", "country": "France"},
    467: {"name": "National 3 - Group H", "country": "France"},
    468: {"name": "National 3 - Group I", "country": "France"},
    469: {"name": "National 3 - Group J", "country": "France"},
    470: {"name": "National 3 - Group K", "country": "France"},
    471: {"name": "National 3 - Group L", "country": "France"},
    472: {"name": "National 3 - Group M", "country": "France"},
    473: {"name": "2. Division - Group 1", "country": "Norway"},
    474: {"name": "2. Division - Group 2", "country": "Norway"},
    475: {"name": "Paulista - A1", "country": "Brazil"},
    476: {"name": "Paulista - A2", "country": "Brazil"},
    477: {"name": "Gaúcho - 1", "country": "Brazil"},
    478: {"name": "Gaúcho - 2", "country": "Brazil"},
    479: {"name": "Canadian Premier League", "country": "Canada"},
    480: {"name": "Olympics Men", "country": "World"},
    481: {"name": "Northern NSW NPL", "country": "Australia"},
    482: {"name": "Queensland NPL", "country": "Australia"},
    483: {"name": "Copa de la Superliga", "country": "Argentina"},
    484: {"name": "Frauenliga", "country": "Austria"},
    485: {"name": "Federation Cup", "country": "Bahrain"},
    486: {"name": "Coppa", "country": "Belarus"},
    487: {"name": "First Amateur Division", "country": "Belgium"},
    488: {"name": "U19 Bundesliga", "country": "Germany"},
    489: {"name": "USL League One", "country": "USA"},
    490: {"name": "World Cup - U20", "country": "World"},
    491: {"name": "Løgmanssteypid", "country": "Faroe-Islands"},
    492: {"name": "Tweede Divisie", "country": "Netherlands"},
    493: {"name": "UEFA U19 Championship", "country": "World"},
    494: {"name": "Super League 2", "country": "Greece"},
    495: {"name": "Hazfi Cup", "country": "Iran"},
    496: {"name": "Liga Alef", "country": "Israel"},
    497: {"name": "Japan Football League", "country": "Japan"},
    498: {"name": "Cup", "country": "Kazakhstan"},
    499: {"name": "Malaysia Cup", "country": "Malaysia"},
    500: {"name": "FA Cup", "country": "Malaysia"},
    501: {"name": "Copa Paraguay", "country": "Paraguay"},
    502: {"name": "Copa Bicentenario", "country": "Peru"},
    503: {"name": "Copa Perú", "country": "Peru"},
    504: {"name": "King's Cup", "country": "Saudi-Arabia"},
    505: {"name": "League Cup", "country": "Singapore"},
    506: {"name": "2. liga", "country": "Slovakia"},
    507: {"name": "Cup", "country": "South-Africa"},
    508: {"name": "League Cup", "country": "South-Africa"},
    509: {"name": "8 Cup", "country": "South-Africa"},
    510: {"name": "1. Liga Promotion", "country": "Switzerland"},
    511: {"name": "Cup", "country": "Tunisia"},
    512: {"name": "2nd Division - Group A", "country": "Albania"},
    513: {"name": "2nd Division - Group B", "country": "Albania"},
    514: {"name": "Coupe Nationale", "country": "Algeria"},
    515: {"name": "U21 League 1", "country": "Algeria"},
    516: {"name": "Super Cup", "country": "Algeria"},
    517: {"name": "Trofeo de Campeones de la Superliga", "country": "Argentina"},
    518: {"name": "Reserve Pro League", "country": "Belgium"},
    519: {"name": "Super Cup", "country": "Belgium"},
    520: {"name": "Acreano", "country": "Brazil"},
    521: {"name": "Amapaense", "country": "Brazil"},
    522: {"name": "Amazonense", "country": "Brazil"},
    523: {"name": "NISA", "country": "USA"},
    524: {"name": "Olympics Women", "country": "World"},
    525: {"name": "UEFA Champions League Women", "country": "World"},
    526: {"name": "Trophée des Champions", "country": "France"},
    527: {"name": "Super Cup", "country": "Chile"},
    528: {"name": "Community Shield", "country": "England"},
    529: {"name": "Super Cup", "country": "Germany"},
    530: {"name": "Super Cup", "country": "Georgia"},
    531: {"name": "UEFA Super Cup", "country": "World"},
    532: {"name": "AFC U23 Asian Cup", "country": "World"},
    533: {"name": "CAF Super Cup", "country": "World"},
    534: {"name": "CONCACAF Caribbean Club Shield", "country": "World"},
    535: {"name": "CECAFA Senior Challenge Cup", "country": "World"},
    536: {"name": "CONCACAF Nations League", "country": "World"},
    537: {"name": "CONCACAF U20", "country": "World"},
    538: {"name": "Africa Cup of Nations U20", "country": "World"},
    539: {"name": "Super Cup", "country": "Egypt"},
    540: {"name": "CONMEBOL Libertadores U20", "country": "World"},
    541: {"name": "CONMEBOL Recopa", "country": "World"},
    542: {"name": "Iraqi League", "country": "Iraq"},
    543: {"name": "Super Cup", "country": "Netherlands"},
    544: {"name": "FA Cup", "country": "Hong-Kong"},
    545: {"name": "AIFF Super Cup", "country": "India"},
    546: {"name": "FAI President's Cup", "country": "Ireland"},
    547: {"name": "Super Cup", "country": "Italy"},
    548: {"name": "Super Cup", "country": "Japan"},
    549: {"name": "Damallsvenskan", "country": "Sweden"},
    550: {"name": "Super Cup", "country": "Portugal"},
    551: {"name": "Super Cup", "country": "Turkey"},
    552: {"name": "3. Lig - Group 1", "country": "Turkey"},
    553: {"name": "3. Lig - Group 2", "country": "Turkey"},
    554: {"name": "3. Lig - Group 3", "country": "Turkey"},
    555: {"name": "Supercupa", "country": "Romania"},
    556: {"name": "Super Cup", "country": "Spain"},
    557: {"name": "Super Cup", "country": "Norway"},
    558: {"name": "Supercopa", "country": "Peru"},
    559: {"name": "League Cup", "country": "Northern-Ireland"},
    560: {"name": "Presidents Cup", "country": "United-Arab-Emirates"},
    561: {"name": "Premier Intermediate League", "country": "Northern-Ireland"},
    562: {"name": "Reserve League", "country": "Belarus"},
    563: {"name": "Ettan - Norra", "country": "Sweden"},
    564: {"name": "Ettan - Södra", "country": "Sweden"},
    565: {"name": "Liga Primera U20", "country": "Nicaragua"},
    566: {"name": "Ligue A", "country": "Burundi"},
    567: {"name": "Ligi kuu Bara", "country": "Tanzania"},
    568: {"name": "Eerste Divisie", "country": "Suriname"},
    569: {"name": "Premier League", "country": "Kyrgyzstan"},
    570: {"name": "Premier League", "country": "Ghana"},
    571: {"name": "Vysshaya Liga", "country": "Tajikistan"},
    572: {"name": "Srpska Liga - Belgrade", "country": "Serbia"},
    573: {"name": "Srpska Liga - Vojvodina", "country": "Serbia"},
    574: {"name": "Srpska Liga - East", "country": "Serbia"},
    575: {"name": "Srpska Liga - West", "country": "Serbia"},
    576: {"name": "Gamma Ethniki - Group 1", "country": "Greece"},
    577: {"name": "Gamma Ethniki - Group 2", "country": "Greece"},
    578: {"name": "Gamma Ethniki - Group 3", "country": "Greece"},
    579: {"name": "Gamma Ethniki - Group 4", "country": "Greece"},
    580: {"name": "Gamma Ethniki - Group 5", "country": "Greece"},
    581: {"name": "Gamma Ethniki - Group 6", "country": "Greece"},
    582: {"name": "Gamma Ethniki - Group 7", "country": "Greece"},
    583: {"name": "Gamma Ethniki - Group 8", "country": "Greece"},
    584: {"name": "Premier League", "country": "Libya"},
    585: {"name": "Premier League", "country": "Uganda"},
    586: {"name": "West Bank Premier League", "country": "Palestine"},
    587: {"name": "World Cup - U17", "country": "World"},
    588: {"name": "National League", "country": "Myanmar"},
    589: {"name": "Taiwan Football Premier League", "country": "Chinese-Taipei"},
    590: {"name": "A Division", "country": "Nepal"},
    591: {"name": "Pro League", "country": "Trinidad-And-Tobago"},
    592: {"name": "Division 2 - Norra Götaland", "country": "Sweden"},
    593: {"name": "Division 2 - Norra Svealand", "country": "Sweden"},
    594: {"name": "Division 2 - Norrland", "country": "Sweden"},
    595: {"name": "Division 2 - Södra Svealand", "country": "Sweden"},
    596: {"name": "Division 2 - Västra Götaland", "country": "Sweden"},
    597: {"name": "Division 2 - Östra Götaland", "country": "Sweden"},
    598: {"name": "Première Division", "country": "Mali"},
    599: {"name": "1. Liga Classic - Group 1", "country": "Switzerland"},
    600: {"name": "1. Liga Classic - Group 2", "country": "Switzerland"},
    601: {"name": "1. Liga Classic - Group 3", "country": "Switzerland"},
    602: {"name": "Baiano - 1", "country": "Brazil"},
    603: {"name": "Paraibano", "country": "Brazil"},
    604: {"name": "Catarinense - 1", "country": "Brazil"},
    605: {"name": "Paulista - A3", "country": "Brazil"},
    606: {"name": "Paranaense - 1", "country": "Brazil"},
    607: {"name": "Roraimense", "country": "Brazil"},
    608: {"name": "Maranhense", "country": "Brazil"},
    609: {"name": "Cearense - 1", "country": "Brazil"},
    610: {"name": "Brasiliense", "country": "Brazil"},
    611: {"name": "Capixaba", "country": "Brazil"},
    612: {"name": "Copa do Nordeste", "country": "Brazil"},
    613: {"name": "Baiano - 2", "country": "Brazil"},
    614: {"name": "Paranaense - 2", "country": "Brazil"},
    615: {"name": "Rondoniense", "country": "Brazil"},
    616: {"name": "Potiguar", "country": "Brazil"},
    617: {"name": "Copa do Brasil U20", "country": "Brazil"},
    618: {"name": "São Paulo Youth Cup", "country": "Brazil"},
    619: {"name": "Mineiro - 2", "country": "Brazil"},
    620: {"name": "Cearense - 2", "country": "Brazil"},
    621: {"name": "Piauiense", "country": "Brazil"},
    622: {"name": "Pernambucano - 1", "country": "Brazil"},
    623: {"name": "Sul-Matogrossense", "country": "Brazil"},
    624: {"name": "Carioca - 1", "country": "Brazil"},
    625: {"name": "Carioca - 2", "country": "Brazil"},
    626: {"name": "Sergipano", "country": "Brazil"},
    627: {"name": "Paraense", "country": "Brazil"},
    628: {"name": "Goiano - 1", "country": "Brazil"},
    629: {"name": "Mineiro - 1", "country": "Brazil"},
    630: {"name": "Matogrossense", "country": "Brazil"},
    631: {"name": "Tocantinense", "country": "Brazil"},
    632: {"name": "Supercopa do Brasil", "country": "Brazil"},
    633: {"name": "NB III - Northeast", "country": "Hungary"},
    634: {"name": "NB III - Southwest", "country": "Hungary"},
    635: {"name": "NB III - Northwest", "country": "Hungary"},
    636: {"name": "Ýokary Liga", "country": "Turkmenistan"},
    637: {"name": "V.League 2", "country": "Vietnam"},
    638: {"name": "Kvindeliga", "country": "Denmark"},
    639: {"name": "Super Cup", "country": "Iceland"},
    640: {"name": "Kansallinen Liiga", "country": "Finland"},
    641: {"name": "NWSL Women - Challenge Cup", "country": "USA"},
    642: {"name": "Curaçao Sekshon Pagá", "country": "Curacao"},
    643: {"name": "3. liga - Bratislava", "country": "Slovakia"},
    644: {"name": "3. liga - West", "country": "Slovakia"},
    645: {"name": "3. liga - East", "country": "Slovakia"},
    646: {"name": "3. liga - Center", "country": "Slovakia"},
    647: {"name": "Lao League", "country": "Laos"},
    648: {"name": "Tasmania NPL", "country": "Australia"},
    649: {"name": "Supreme Division Women", "country": "Russia"},
    650: {"name": "Second League - Group 3", "country": "Russia"},
    651: {"name": "Second League - Group 1", "country": "Russia"},
    652: {"name": "Second League - Group 2", "country": "Russia"},
    653: {"name": "Second League - Group 4", "country": "Russia"},
    654: {"name": "Super Cup", "country": "Armenia"},
    655: {"name": "Copa Constitució", "country": "Andorra"},
    656: {"name": "Super Cup", "country": "Bulgaria"},
    657: {"name": "Cup", "country": "Estonia"},
    658: {"name": "Cup", "country": "Latvia"},
    659: {"name": "Super Cup", "country": "Israel"},
    660: {"name": "WK-League", "country": "South-Korea"},
    661: {"name": "Cup", "country": "Lithuania"},
    662: {"name": "Copa por México", "country": "Mexico"},
    663: {"name": "Super Cup", "country": "Russia"},
    664: {"name": "Superliga", "country": "Kosovo"},
    665: {"name": "Cup", "country": "Kosovo"},
    666: {"name": "Friendlies Women", "country": "World"},
    667: {"name": "Friendlies Clubs", "country": "World"},
    668: {"name": "1. Liga U19", "country": "Czech-Republic"},
    669: {"name": "1. Liga Women", "country": "Czech-Republic"},
    670: {"name": "Community Shield Women", "country": "England"},
    671: {"name": "Úrvalsdeild Women", "country": "Iceland"},
    672: {"name": "David Kipiani Cup", "country": "Georgia"},
    673: {"name": "Liga MX Femenil", "country": "Mexico"},
    674: {"name": "Cupa", "country": "Moldova"},
    675: {"name": "U21 Divisie 1", "country": "Netherlands"},
    676: {"name": "Central Youth League", "country": "Poland"},
    677: {"name": "QSL Cup", "country": "Qatar"},
    678: {"name": "Super Cup", "country": "Ukraine"},
    679: {"name": "U21 League", "country": "Ukraine"},
    680: {"name": "Cup", "country": "Slovakia"},
    681: {"name": "Campeonato de Portugal Prio - Group E", "country": "Portugal"},
    682: {"name": "Campeonato de Portugal Prio - Group F", "country": "Portugal"},
    683: {"name": "Campeonato de Portugal Prio - Group G", "country": "Portugal"},
    684: {"name": "Campeonato de Portugal Prio - Group H", "country": "Portugal"},
    685: {"name": "3. liga - CFL B", "country": "Czech-Republic"},
    686: {"name": "4. liga - Divizie F", "country": "Czech-Republic"},
    687: {"name": "Regionalliga - Tirol", "country": "Austria"},
    688: {"name": "Regionalliga - Salzburg", "country": "Austria"},
    689: {"name": "Third Amateur Division - ACFF A", "country": "Belgium"},
    690: {"name": "Third Amateur Division - ACFF B", "country": "Belgium"},
    691: {"name": "Provincial - Brabant ACFF", "country": "Belgium"},
    692: {"name": "Primera División RFEF - Group 5", "country": "Spain"},
    693: {"name": "Gamma Ethniki - Group 9", "country": "Greece"},
    694: {"name": "Gamma Ethniki - Group 10", "country": "Greece"},
    695: {"name": "U18 Premier League - North", "country": "England"},
    696: {"name": "U18 Premier League - South", "country": "England"},
    697: {"name": "WSL Cup", "country": "England"},
    698: {"name": "FA Women's Cup", "country": "England"},
    699: {"name": "Women's Championship", "country": "England"},
    700: {"name": "Kakkosen Cup", "country": "Finland"},
    701: {"name": "Liga Revelação U23", "country": "Portugal"},
    702: {"name": "Premier League 2 Division One", "country": "England"},
    703: {"name": "Professional Development League", "country": "England"},
    704: {"name": "Coppa Italia Primavera", "country": "Italy"},
    705: {"name": "Campionato Primavera - 1", "country": "Italy"},
    706: {"name": "Campionato Primavera - 2", "country": "Italy"},
    707: {"name": "Cup", "country": "Albania"},
    708: {"name": "Super Cup", "country": "Albania"},
    709: {"name": "Cup", "country": "Armenia"},
    710: {"name": "Nacional B", "country": "Bolivia"},
    711: {"name": "Segunda División", "country": "Chile"},
    712: {"name": "Liga Femenina", "country": "Colombia"},
    713: {"name": "Superliga", "country": "Colombia"},
    714: {"name": "Cup", "country": "Egypt"},
    715: {"name": "DFB Junioren Pokal", "country": "Germany"},
    716: {"name": "Senior Shield", "country": "Hong-Kong"},
    717: {"name": "I-League - 2nd Division", "country": "India"},
    718: {"name": "Piala Indonesia", "country": "Indonesia"},
    719: {"name": "Super Cup", "country": "Kuwait"},
    720: {"name": "Emir Cup", "country": "Kuwait"},
    721: {"name": "Cup", "country": "Luxembourg"},
    722: {"name": "Liga Premier Serie A", "country": "Mexico"},
    723: {"name": "Cup", "country": "Montenegro"},
    724: {"name": "U18 Divisie 1", "country": "Netherlands"},
    725: {"name": "Toppserien", "country": "Norway"},
    726: {"name": "Sultan Cup", "country": "Oman"},
    727: {"name": "Super Cup", "country": "Poland"},
    728: {"name": "Liga 1 Feminin", "country": "Romania"},
    729: {"name": "Coppa Titano", "country": "San-Marino"},
    730: {"name": "Football League - Highland League", "country": "Scotland"},
    731: {"name": "Football League - Lowland League", "country": "Scotland"},
    732: {"name": "Cup", "country": "Serbia"},
    733: {"name": "I Liga - Women", "country": "Slovakia"},
    734: {"name": "Diski Challenge", "country": "South-Africa"},
    735: {"name": "Copa Federacion", "country": "Spain"},
    736: {"name": "Elitettan", "country": "Sweden"},
    737: {"name": "Svenska Cupen - Women", "country": "Sweden"},
    738: {"name": "League Cup", "country": "Wales"},
    739: {"name": "AXA Women’s Super League", "country": "Switzerland"},
    740: {"name": "Brasileiro U20 A", "country": "Brazil"},
    741: {"name": "Brasileiro de Aspirantes", "country": "Brazil"},
    742: {"name": "Copa Paulista", "country": "Brazil"},
    743: {"name": "UEFA Championship - Women", "country": "World"},
    744: {"name": "Oberliga - Schleswig-Holstein", "country": "Germany"},
    745: {"name": "Oberliga - Hamburg", "country": "Germany"},
    746: {"name": "Oberliga - Mittelrhein", "country": "Germany"},
    747: {"name": "Oberliga - Westfalen", "country": "Germany"},
    748: {"name": "Oberliga - Niedersachsen", "country": "Germany"},
    749: {"name": "Oberliga - Bremen", "country": "Germany"},
    750: {"name": "Oberliga - Hessen", "country": "Germany"},
    751: {"name": "Oberliga - Niederrhein", "country": "Germany"},
    752: {"name": "Oberliga - Rheinland-Pfalz / Saar", "country": "Germany"},
    753: {"name": "Oberliga - Baden-Württemberg", "country": "Germany"},
    754: {"name": "Oberliga - Nordost-Nord", "country": "Germany"},
    755: {"name": "Oberliga - Nordost-Süd", "country": "Germany"},
    756: {"name": "Cup", "country": "Macedonia"},
    757: {"name": "Irish Cup", "country": "Northern-Ireland"},
    758: {"name": "Premier Division", "country": "Gibraltar"},
    759: {"name": "Liga Mayor", "country": "Dominican-Republic"},
    760: {"name": "LFA First Division", "country": "Liberia"},
    761: {"name": "Cup", "country": "Liechtenstein"},
    762: {"name": "Premier League", "country": "Mauritania"},
    763: {"name": "Mauritian League", "country": "Mauritius"},
    764: {"name": "Premier League", "country": "Mongolia"},
    765: {"name": "PFL", "country": "Philippines"},
    766: {"name": "China Cup", "country": "World"},
    767: {"name": "CONCACAF League", "country": "World"},
    768: {"name": "Arab Club Champions Cup", "country": "World"},
    769: {"name": "Premier League Asia Trophy", "country": "World"},
    770: {"name": "Pacific Games", "country": "World"},
    771: {"name": "COSAFA U20 Championship", "country": "World"},
    772: {"name": "Leagues Cup", "country": "World"},
    773: {"name": "Sudamericano U20", "country": "World"},
    774: {"name": "3. Division - Girone 1", "country": "Norway"},
    775: {"name": "3. Division - Girone 2", "country": "Norway"},
    776: {"name": "3. Division - Girone 3", "country": "Norway"},
    777: {"name": "3. Division - Girone 4", "country": "Norway"},
    778: {"name": "3. Division - Girone 5", "country": "Norway"},
    779: {"name": "3. Division - Girone 6", "country": "Norway"},
    780: {"name": "III Liga - Group 1", "country": "Poland"},
    781: {"name": "III Liga - Group 2", "country": "Poland"},
    782: {"name": "III Liga - Group 3", "country": "Poland"},
    783: {"name": "III Liga - Group 4", "country": "Poland"},
    784: {"name": "Liga III - Serie 1", "country": "Romania"},
    785: {"name": "Liga III - Serie 2", "country": "Romania"},
    786: {"name": "Liga III - Serie 3", "country": "Romania"},
    787: {"name": "Liga III - Serie 4", "country": "Romania"},
    788: {"name": "Liga III - Serie 5", "country": "Romania"},
    789: {"name": "Liga III - Serie 6", "country": "Romania"},
    790: {"name": "Liga III - Serie 7", "country": "Romania"},
    791: {"name": "Liga III - Serie 8", "country": "Romania"},
    792: {"name": "Liga III - Serie 9", "country": "Romania"},
    793: {"name": "Liga III - Serie 10", "country": "Romania"},
    794: {"name": "3. SNL - East", "country": "Slovenia"},
    795: {"name": "3. SNL - West", "country": "Slovenia"},
    796: {"name": "2. Liga Interregional - Group 1", "country": "Switzerland"},
    797: {"name": "2. Liga Interregional - Group 2", "country": "Switzerland"},
    798: {"name": "2. Liga Interregional - Group 3", "country": "Switzerland"},
    799: {"name": "2. Liga Interregional - Group 4", "country": "Switzerland"},
    800: {"name": "2. Liga Interregional - Group 5", "country": "Switzerland"},
    801: {"name": "2. Liga Interregional - Group 6", "country": "Switzerland"},
    802: {"name": "Cup", "country": "Uzbekistan"},
    803: {"name": "Asian Games", "country": "World"},
    804: {"name": "Caribbean Cup", "country": "World"},
    805: {"name": "Copa Centroamericana", "country": "World"},
    806: {"name": "OFC Nations Cup", "country": "World"},
    807: {"name": "AFC Challenge Cup", "country": "World"},
    808: {"name": "CONCACAF Nations League - Qualification", "country": "World"},
    809: {"name": "Super Cup", "country": "Andorra"},
    810: {"name": "Super Copa", "country": "Argentina"},
    811: {"name": "Federation Cup", "country": "Bangladesh"},
    812: {"name": "Super Cup", "country": "Belarus"},
    813: {"name": "Elite Two", "country": "Cameroon"},
    814: {"name": "Reykjavik Cup", "country": "Iceland"},
    815: {"name": "Fotbolti.net Cup A", "country": "Iceland"},
    816: {"name": "Shield Cup", "country": "Jordan"},
    817: {"name": "Super Cup Primavera", "country": "Italy"},
    818: {"name": "Super Cup", "country": "Kazakhstan"},
    819: {"name": "Super Cup", "country": "Kosovo"},
    820: {"name": "Crown Prince Cup", "country": "Kuwait"},
    821: {"name": "FA Trophy", "country": "Malta"},
    822: {"name": "Cup", "country": "Morocco"},
    823: {"name": "Nasjonal U19 Champions League", "country": "Norway"},
    824: {"name": "Emir Cup", "country": "Qatar"},
    825: {"name": "Qatar Cup", "country": "Qatar"},
    826: {"name": "Super Cup", "country": "Saudi-Arabia"},
    827: {"name": "Crown Prince Cup", "country": "Saudi-Arabia"},
    828: {"name": "Ligue 2", "country": "Tunisia"},
    829: {"name": "Youth League", "country": "Turkmenistan"},
    830: {"name": "Super Cup", "country": "Uzbekistan"},
    831: {"name": "Super Cup", "country": "Vietnam"},
    832: {"name": "Coupe de la Ligue", "country": "Algeria"},
    833: {"name": "Queensland Premier League", "country": "Australia"},
    834: {"name": "South Australia State League 1", "country": "Australia"},
    835: {"name": "New South Wales NPL 2", "country": "Australia"},
    836: {"name": "Victoria NPL 2", "country": "Australia"},
    837: {"name": "Rock Cup", "country": "Gibraltar"},
    838: {"name": "Super Cup", "country": "Jordan"},
    839: {"name": "Super Cup", "country": "Lithuania"},
    840: {"name": "Taça Revelação U23", "country": "Portugal"},
    841: {"name": "QFA Cup", "country": "Qatar"},
    842: {"name": "Super Copa", "country": "Uruguay"},
    843: {"name": "Copa Verde", "country": "Brazil"},
    844: {"name": "Ligue 1", "country": "Congo"},
    845: {"name": "GFA League", "country": "Gambia"},
    846: {"name": "Somali Premier League", "country": "Somalia"},
    847: {"name": "Premier League", "country": "Eswatini"},
    848: {"name": "UEFA Europa Conference League", "country": "World"},
    849: {"name": "Baltic Cup", "country": "World"},
    850: {"name": "UEFA U21 Championship - Qualification", "country": "World"},
    851: {"name": "Carioca A2", "country": "Brazil"},
    852: {"name": "Super Cup", "country": "Cyprus"},
    853: {"name": "Supercopa de Ecuador", "country": "Ecuador"},
    854: {"name": "WE League", "country": "Japan"},
    855: {"name": "Dhivehi Premier League", "country": "Maldives"},
    856: {"name": "CONCACAF Caribbean Club Championship", "country": "World"},
    857: {"name": "Campeón de Campeones", "country": "Mexico"},
    858: {"name": "CONCACAF Gold Cup - Qualification", "country": "World"},
    859: {"name": "COSAFA Cup", "country": "World"},
    860: {"name": "Arab Cup", "country": "World"},
    861: {"name": "U20 League", "country": "Mexico"},
    862: {"name": "3. Division", "country": "Denmark"},
    863: {"name": "Cup", "country": "Jordan"},
    864: {"name": "Supercopa", "country": "Costa-Rica"},
    865: {"name": "Liga 3", "country": "Portugal"},
    866: {"name": "MLS All-Star", "country": "USA"},
    867: {"name": "Copa Paulino Alcantara", "country": "Philippines"},
    868: {"name": "Premier League", "country": "Pakistan"},
    869: {"name": "CECAFA Club Cup", "country": "World"},
    870: {"name": "Premier League", "country": "Crimea"},
    871: {"name": "Premier League Cup", "country": "England"},
    872: {"name": "Liga Premier Serie B", "country": "Mexico"},
    873: {"name": "Thai Champions Cup", "country": "Thailand"},
    874: {"name": "Australia Cup", "country": "Australia"},
    875: {"name": "Segunda División RFEF - Group 1", "country": "Spain"},
    876: {"name": "Segunda División RFEF - Group 2", "country": "Spain"},
    877: {"name": "Segunda División RFEF - Group 3", "country": "Spain"},
    878: {"name": "Segunda División RFEF - Group 4", "country": "Spain"},
    879: {"name": "Segunda División RFEF - Group 5", "country": "Spain"},
    880: {"name": "World Cup - Women - Qualification Europe", "country": "World"},
    881: {"name": "Olympics Men - Qualification Concacaf", "country": "World"},
    882: {"name": "Olympics Women - Qualification Asia", "country": "World"},
    883: {"name": "Reserve League", "country": "Netherlands"},
    884: {"name": "Super Cup", "country": "San-Marino"},
    885: {"name": "Campeones Cup", "country": "World"},
    886: {"name": "UEFA U17 Championship - Qualification", "country": "World"},
    887: {"name": "Second League", "country": "Egypt"},
    888: {"name": "Second League - Group B", "country": "Egypt"},
    889: {"name": "Second League - Group C", "country": "Egypt"},
    890: {"name": "U20 Elite League", "country": "World"},
    891: {"name": "Coppa Italia Serie C", "country": "Italy"},
    892: {"name": "Coppa Italia Serie D", "country": "Italy"},
    893: {"name": "UEFA U19 Championship - Qualification", "country": "World"},
    894: {"name": "Asian Cup Women - Qualification", "country": "World"},
    895: {"name": "League Cup", "country": "Egypt"},
    896: {"name": "Super Cup", "country": "United-Arab-Emirates"},
    897: {"name": "Asian Cup Women", "country": "World"},
    898: {"name": "League Cup", "country": "Thailand"},
    899: {"name": "League Cup", "country": "Finland"},
    900: {"name": "Tipsport Malta Cup", "country": "World"},
    901: {"name": "Ykköscup", "country": "Finland"},
    902: {"name": "Algarve Cup", "country": "World"},
    903: {"name": "The Atlantic Cup", "country": "World"},
    904: {"name": "SheBelieves Cup", "country": "World"},
    905: {"name": "Super Cup", "country": "Iran"},
    906: {"name": "Reserve League", "country": "Argentina"},
    907: {"name": "Primera Division", "country": "Cuba"},
    908: {"name": "ASEAN Championship U23", "country": "World"},
    909: {"name": "MLS Next Pro", "country": "USA"},
    910: {"name": "Youth Viareggio Cup", "country": "World"},
    911: {"name": "Southeast Asian Games", "country": "World"},
    912: {"name": "CONCACAF Women U17", "country": "World"},
    913: {"name": "CONMEBOL - UEFA Finalissima", "country": "World"},
    914: {"name": "Tournoi Maurice Revello", "country": "World"},
    915: {"name": "1. Division Women", "country": "Norway"},
    916: {"name": "Kirin Cup", "country": "World"},
    917: {"name": "Copa Ecuador", "country": "Ecuador"},
    918: {"name": "UEFA U19 Championship - Women", "country": "World"},
    919: {"name": "Mediterranean Games", "country": "World"},
    920: {"name": "World Cup - U20 - Women", "country": "World"},
    921: {"name": "UEFA U17 Championship", "country": "World"},
    922: {"name": "Africa Cup of Nations - Women", "country": "World"},
    923: {"name": "League 1 Ontario", "country": "Canada"},
    924: {"name": "Piala Presiden", "country": "Indonesia"},
    925: {"name": "Super Cup", "country": "Czech-Republic"},
    926: {"name": "Copa America Femenina", "country": "World"},
    927: {"name": "World Cup - Women - Qualification Concacaf", "country": "World"},
    928: {"name": "ASEAN Championship U19", "country": "World"},
    929: {"name": "League Two", "country": "China"},
    930: {"name": "Copa Uruguay", "country": "Uruguay"},
    931: {"name": "Non League Premier - Southern Central", "country": "England"},
    932: {"name": "Non League Div One - Northern East", "country": "England"},
    933: {"name": "Non League Div One - Southern Central", "country": "England"},
    934: {"name": "Arab Championship - U20", "country": "World"},
    935: {"name": "Diski Shield", "country": "South-Africa"},
    936: {"name": "Catarinense - 2", "country": "Brazil"},
    937: {"name": "Emirates Cup", "country": "World"},
    938: {"name": "Oberliga - Bayern Nord", "country": "Germany"},
    939: {"name": "Oberliga - Bayern Süd", "country": "Germany"},
    940: {"name": "COTIF Tournament", "country": "World"},
    941: {"name": "Islamic Solidarity Games", "country": "World"},
    942: {"name": "Serie C - Girone B", "country": "Italy"},
    943: {"name": "Serie C - Girone C", "country": "Italy"},
    944: {"name": "Super Cup", "country": "Oman"},
    945: {"name": "International Champions Cup - Women", "country": "World"},
    946: {"name": "Second NL", "country": "Croatia"},
    947: {"name": "DFB Pokal - Women", "country": "Germany"},
    948: {"name": "1a Divisão - Women", "country": "Portugal"},
    949: {"name": "CONMEBOL Libertadores Femenina", "country": "World"},
    950: {"name": "World Cup - U17 - Women", "country": "World"},
    951: {"name": "South American Youth Games", "country": "World"},
    952: {"name": "AFC U23 Asian Cup - Qualification", "country": "World"},
    953: {"name": "Africa U23 Cup of Nations - Qualification", "country": "World"},
    954: {"name": "National League - Central", "country": "New-Zealand"},
    955: {"name": "National League - National", "country": "New-Zealand"},
    956: {"name": "National League - Northern", "country": "New-Zealand"},
    957: {"name": "National League - Southern", "country": "New-Zealand"},
    958: {"name": "Copa Costa Rica", "country": "Costa-Rica"},
    959: {"name": "Cup", "country": "Singapore"},
    960: {"name": "Euro Championship - Qualification", "country": "World"},
    961: {"name": "Supercopa", "country": "Paraguay"},
    962: {"name": "Premier League", "country": "Lesotho"},
    963: {"name": "CONCACAF U17", "country": "World"},
    964: {"name": "Copa de la División Profesional", "country": "Bolivia"},
    965: {"name": "AFC U20 Asian Cup", "country": "World"},
    966: {"name": "Cup", "country": "Ghana"},
    967: {"name": "Cup", "country": "Lebanon"},
    968: {"name": "Championnat D1", "country": "Gabon"},
    969: {"name": "Primeira Divisão", "country": "Macao"},
    970: {"name": "CONMEBOL - U17", "country": "World"},
    971: {"name": "Shield Cup", "country": "Kenya"},
    972: {"name": "Super Cup", "country": "China"},
    973: {"name": "CAF Cup of Nations - U17", "country": "World"},
    974: {"name": "Serie C - Supercoppa Lega Finals", "country": "Italy"},
    975: {"name": "Serie C - Relegation - Play-offs", "country": "Italy"},
    976: {"name": "Serie C - Promotion - Play-offs", "country": "Italy"},
    977: {"name": "Tercera División RFEF - Promotion - Play-offs", "country": "Spain"},
    978: {"name": "2nd Division - Play-offs", "country": "Albania"},
    979: {"name": "Provincial - Play-offs VV", "country": "Belgium"},
    980: {"name": "Provincial - Play-offs ACFF", "country": "Belgium"},
    981: {"name": "Third Amateur Division - Play-offs", "country": "Belgium"},
    982: {"name": "Denmark Series - Promotion Round", "country": "Denmark"},
    983: {"name": "Denmark Series - Relegation Round", "country": "Denmark"},
    984: {"name": "National League - North - Play-offs", "country": "England"},
    985: {"name": "National League - South - Play-offs", "country": "England"},
    986: {"name": "Non League Div One - Play-offs", "country": "England"},
    987: {"name": "U18 Premier League - Championship", "country": "England"},
    988: {"name": "Oberliga - Promotion Round", "country": "Germany"},
    989: {"name": "Oberliga - Relegation Round", "country": "Germany"},
    990: {"name": "Gamma Ethniki - Promotion Group", "country": "Greece"},
    991: {"name": "Campeonato de Portugal Prio - Promotion Round", "country": "Portugal"},
    992: {"name": "Football League - Championship", "country": "Scotland"},
    993: {"name": "Non League Premier - Isthmian - Play-offs", "country": "England"},
    994: {"name": "Non League Premier - Northern - Play-offs", "country": "England"},
    995: {"name": "Non League Premier - Southern South - Play-offs", "country": "England"},
    996: {"name": "Non League Premier - Southern Central - Play-offs", "country": "England"},
    997: {"name": "Serie D - Promotion - Play-offs", "country": "Italy"},
    998: {"name": "Serie D - Relegation - Play-offs", "country": "Italy"},
    999: {"name": "Serie D - Championship Round", "country": "Italy"},
    1000: {"name": "Segunda División RFEF - Play-offs", "country": "Spain"},
    1001: {"name": "CONCACAF Women U20", "country": "World"},
    1002: {"name": "Regionalliga - Promotion Play-offs", "country": "Germany"},
    1003: {"name": "Regionalliga - Relegation Round", "country": "Germany"},
    1004: {"name": "Derde Divisie - Relegation Round", "country": "Netherlands"},
    1005: {"name": "1. Liga Classic - Play-offs", "country": "Switzerland"},
    1006: {"name": "Primera División RFEF - Play Offs", "country": "Spain"},
    1007: {"name": "3. Lig - Play-offs", "country": "Turkey"},
    1008: {"name": "CAFA Nations Cup", "country": "World"},
    1009: {"name": "Liga III - Play-offs", "country": "Romania"},
    1010: {"name": "3. liga - Promotion Play-off", "country": "Czech-Republic"},
    1011: {"name": "Second Amateur Division - Play-offs ", "country": "Belgium"},
    1012: {"name": "AFC U17 Asian Cup", "country": "World"},
    1013: {"name": "All-Island Cup - Women", "country": "World"},
    1014: {"name": "Second League - Play-offs", "country": "Egypt"},
    1015: {"name": "CAF U23 Cup of Nations", "country": "World"},
    1016: {"name": "CAC Games", "country": "World"},
    1017: {"name": "U23 League", "country": "Mexico"},
    1018: {"name": "Federation Cup", "country": "Lebanon"},
    1019: {"name": "Charity Shield", "country": "Northern-Ireland"},
    1020: {"name": "Calcutta Premier Division", "country": "India"},
    1021: {"name": "Super Cup", "country": "Croatia"},
    1022: {"name": "Premier League - Summer Series", "country": "England"},
    1023: {"name": "NB III - Southeast", "country": "Hungary"},
    1024: {"name": "UEFA - CONMEBOL - Club Challenge", "country": "World"},
    1025: {"name": "Second League A - Division A Gold", "country": "Russia"},
    1026: {"name": "Second League A - Division A Silver", "country": "Russia"},
    1027: {"name": "3. Lig - Group 4", "country": "Turkey"},
    1028: {"name": "CONCACAF Central American Cup", "country": "World"},
    1029: {"name": "National 3 - Group G", "country": "France"},
    1030: {"name": "Goiano - 2", "country": "Brazil"},
    1031: {"name": "Premier League", "country": "Bhutan"},
    1032: {"name": "Copa de la Liga Profesional", "country": "Argentina"},
    1033: {"name": "Ekstraliga Women", "country": "Poland"},
    1034: {"name": "2. Frauen Bundesliga", "country": "Germany"},
    1035: {"name": "Copa Rio", "country": "Brazil"},
    1036: {"name": "Copa Santa Catarina", "country": "Brazil"},
    1037: {"name": "Paraibano 2", "country": "Brazil"},
    1038: {"name": "King's Cup", "country": "World"},
    1039: {"name": "Premier League International Cup", "country": "World"},
    1040: {"name": "UEFA Nations League - Women", "country": "World"},
    1041: {"name": "Júniores U19", "country": "Portugal"},
    1042: {"name": "Super Cup", "country": "Gibraltar"},
    1043: {"name": "African Football League", "country": "World"},
    1044: {"name": "Erste Liga Cup", "country": "Switzerland"},
    1045: {"name": "Pan American Games", "country": "World"},
    1046: {"name": "CONCACAF Gold Cup - Qualification - Women", "country": "World"},
    1047: {"name": "Olympics Women - Qualification CAF", "country": "World"},
    1048: {"name": "Premier Division", "country": "Antigua-And-Barbuda"},
    1049: {"name": "King's Cup", "country": "Bahrain"},
    1050: {"name": "Super Cup", "country": "Malta"},
    1051: {"name": "HKPL Cup", "country": "Hong-Kong"},
    1052: {"name": "Kakkonen - Play-offs", "country": "Finland"},
    1053: {"name": "Division 2 - Play-offs", "country": "Sweden"},
    1054: {"name": "2. Division - Play-offs", "country": "Norway"},
    1055: {"name": "Ettan - Relegation Round", "country": "Sweden"},
    1056: {"name": "National League - Championship - Final", "country": "New-Zealand"},
    1057: {"name": "CONCACAF Gold Cup - Women", "country": "World"},
    1058: {"name": "Supercopa Femenina", "country": "Spain"},
    1059: {"name": "Recopa Catarinense", "country": "Brazil"},
    1060: {"name": "CONMEBOL - Pre-Olympic Tournament", "country": "World"},
    1061: {"name": "Second League A - Spring Season Gold", "country": "Russia"},
    1062: {"name": "Paulista - A4", "country": "Brazil"},
    1063: {"name": "Copa Alagoas", "country": "Brazil"},
    1064: {"name": "Second League A - Spring Season Silver", "country": "Russia"},
    1065: {"name": "U19 League", "country": "Ukraine"},
    1066: {"name": "CONCACAF U20 - Qualification", "country": "World"},
    1067: {"name": "Torneo Promocional Amateur", "country": "Argentina"},
    1068: {"name": "FA Youth Cup", "country": "England"},
    1069: {"name": "Goiano U20", "country": "Brazil"},
    1070: {"name": "AFC U20 Asian Cup - Women", "country": "World"},
    1071: {"name": "Paranaense U20", "country": "Brazil"},
    1072: {"name": "All Africa Games", "country": "World"},
    1073: {"name": "Baiano U20", "country": "Brazil"},
    1074: {"name": "SWPL Cup", "country": "Scotland"},
    1075: {"name": "Pro League A", "country": "Uzbekistan"},
    1076: {"name": "Catarinense U20", "country": "Brazil"},
    1077: {"name": "WAFF Championship U23", "country": "World"},
    1078: {"name": "SWF Scottish Cup", "country": "Scotland"},
    1079: {"name": "Yemeni League", "country": "Yemen"},
    1080: {"name": "Premier Division", "country": "Grenada"},
    1081: {"name": "CONMEBOL - U17 Femenino", "country": "World"},
    1082: {"name": "Copa Rio U20", "country": "Brazil"},
    1083: {"name": "UEFA Championship - Women - Qualification", "country": "World"},
    1084: {"name": "Championnat National", "country": "Togo"},
    1085: {"name": "CONMEBOL U20 Femenino", "country": "World"},
    1086: {"name": "Paulista - U20", "country": "Brazil"},
    1087: {"name": "Ykkösliiga", "country": "Finland"},
    1088: {"name": "Pernambucano - U20", "country": "Brazil"},
    1089: {"name": "UAE-Qatar - Super Shield", "country": "World"},
    1090: {"name": "NNSW League 1", "country": "Australia"},
    1091: {"name": "Tasmania Northern Championship", "country": "Australia"},
    1092: {"name": "Capital Territory NPL 2", "country": "Australia"},
    1093: {"name": "Tasmania Southern Championship", "country": "Australia"},
    1094: {"name": "Western Australia State League 1", "country": "Australia"},
    1095: {"name": "USL League One Cup", "country": "USA"},
    1096: {"name": "Matogrossense 2", "country": "Brazil"},
    1097: {"name": "Copa Espírito Santo", "country": "Brazil"},
    1098: {"name": "Paulista Série B", "country": "Brazil"},
    1099: {"name": "Gamma Ethniki - Relegation Play-offs", "country": "Greece"},
    1100: {"name": "Brasiliense U20", "country": "Brazil"},
    1101: {"name": "AFC U17 Asian Cup - Women", "country": "World"},
    1102: {"name": "UEFA U17 Championship - Women", "country": "World"},
    1103: {"name": "Premiership Women", "country": "Northern-Ireland"},
    1104: {"name": "Liga 3", "country": "Georgia"},
    1105: {"name": "Olympics - Intercontinental Play-offs", "country": "World"},
    1106: {"name": "Carioca C", "country": "Brazil"},
    1107: {"name": "Mineiro U20", "country": "Brazil"},
    1108: {"name": "Sergipano U20", "country": "Brazil"},
    1109: {"name": "Super Cup", "country": "Bahrain"},
    1110: {"name": "Alagoano U20", "country": "Brazil"},
    1111: {"name": "NB III - Promotion Play-offs", "country": "Hungary"},
    1112: {"name": "Cearense U20", "country": "Brazil"},
    1113: {"name": "Copa Venezuela", "country": "Venezuela"},
    1114: {"name": "Carioca U20", "country": "Brazil"},
    1115: {"name": "Paraense A3", "country": "Brazil"},
    1116: {"name": "WPSL", "country": "USA"},
    1117: {"name": "USL W League", "country": "USA"},
    1118: {"name": "NPSL", "country": "USA"},
    1119: {"name": "NWSL - Liga MXF Summer Cup", "country": "USA"},
    1120: {"name": "Paraibano U20", "country": "Brazil"},
    1121: {"name": "Second League A - Promotion Play-offs", "country": "Russia"},
    1122: {"name": "OFC U19 Championship", "country": "World"},
    1123: {"name": "UAE-Qatar - Super Cup", "country": "World"},
    1124: {"name": "Cearense - 3", "country": "Brazil"},
    1125: {"name": "Pernambucano - 2", "country": "Brazil"},
    1126: {"name": "Esiliiga B", "country": "Estonia"},
    1127: {"name": "Chatham Cup", "country": "New-Zealand"},
    1128: {"name": "Brasileiro U17", "country": "Brazil"},
    1129: {"name": "ASEAN Club Championship", "country": "World"},
    1130: {"name": "USL Super League", "country": "USA"},
    1131: {"name": "Super Cup", "country": "Mongolia"},
    1132: {"name": "AFC Challenge League", "country": "World"},
    1133: {"name": "Goiano - 3", "country": "Brazil"},
    1134: {"name": "Amazonense - 2", "country": "Brazil"},
    1135: {"name": "Sergipano - 2", "country": "Brazil"},
    1136: {"name": "CONCACAF W Champions Cup", "country": "World"},
    1137: {"name": "Supercup der Frauen", "country": "Germany"},
    1138: {"name": "Paranaense - 3", "country": "Brazil"},
    1139: {"name": "Potiguar - U20", "country": "Brazil"},
    1140: {"name": "AFC Women's Champions League", "country": "World"},
    1141: {"name": "Brasiliense B", "country": "Brazil"},
    1142: {"name": "Mineiro - 3", "country": "Brazil"},
    1143: {"name": "Estadual Junior U20", "country": "Brazil"},
    1144: {"name": "Super Cup", "country": "Ghana"},
    1145: {"name": "Paraense B1", "country": "Brazil"},
    1146: {"name": "Alagoano - 2", "country": "Brazil"},
    1147: {"name": "Capixaba B", "country": "Brazil"},
    1148: {"name": "Maranhense - 2", "country": "Brazil"},
    1149: {"name": "Potiguar - 2", "country": "Brazil"},
    1150: {"name": "Gaúcho - 3", "country": "Brazil"},
    1151: {"name": "Pernambucano - 3", "country": "Brazil"},
    1152: {"name": "U19 Divisie 1", "country": "Netherlands"},
    1153: {"name": "AFC U20 Asian Cup - Qualification", "country": "World"},
    1154: {"name": "Catarinense - 3", "country": "Brazil"},
    1155: {"name": "Carioca B2", "country": "Brazil"},
    1156: {"name": "National League Cup", "country": "England"},
    1157: {"name": "Paraense U20", "country": "Brazil"},
    1158: {"name": "Copa Gaúcha", "country": "Brazil"},
    1159: {"name": "CECAFA U20 Championship", "country": "World"},
    1160: {"name": "Sapling Cup", "country": "Hong-Kong"},
    1161: {"name": "AFC U17 Asian Cup - Qualification", "country": "World"},
    1162: {"name": "AGCFF Gulf Champions League", "country": "World"},
    1163: {"name": "African Nations Championship - Qualification", "country": "World"},
    1164: {"name": "CAF Women's Champions League", "country": "World"},
    1165: {"name": "Copa Fares Lopes", "country": "Brazil"},
    1166: {"name": "Super Cup", "country": "Cameroon"},
    1167: {"name": "Recopa", "country": "Costa-Rica"},
    1168: {"name": "FIFA Intercontinental Cup", "country": "World"},
    1169: {"name": "EAFF E-1 Football Championship - Qualification", "country": "World"},
    1170: {"name": "MFL Cup", "country": "Malaysia"},
    1171: {"name": "Coppa Italia Women", "country": "Italy"},
    1172: {"name": "Torneo Amistoso de Verano", "country": "Bolivia"},
    1173: {"name": "Challenge Cup", "country": "Malta"},
    1174: {"name": "Hun Sen Cup", "country": "Cambodia"},
    1175: {"name": "Women's President's Cup", "country": "Ireland"},
    1176: {"name": "Super Cup", "country": "Latvia"},
    1177: {"name": "Super Cup", "country": "Faroe-Islands"},
    1178: {"name": "Super Copa International", "country": "Argentina"},
    1179: {"name": "Copa do Brasil U17", "country": "Brazil"},
    1180: {"name": "Copa LDF", "country": "Dominican-Republic"},
    1181: {"name": "Supercopa", "country": "Venezuela"},
    1182: {"name": "Northern Super League", "country": "Canada"},
    1183: {"name": "Brasileiro U20 B", "country": "Brazil"},
    1184: {"name": "Copa Grão Pará", "country": "Brazil"},
    1185: {"name": "3. liga - Play-offs", "country": "Slovakia"},
    1186: {"name": "FIFA Club World Cup - Play-In", "country": "World"},
    1187: {"name": "Copa Nicaragua", "country": "Nicaragua"},
    1188: {"name": "EAFF E-1 Football Championship - Women", "country": "World"},
    1189: {"name": "Asean Championship Women", "country": "World"},
    1190: {"name": "Super Cup Women", "country": "Netherlands"},
    1191: {"name": "UEFA Europa Cup - Women", "country": "World"},
    1192: {"name": "Super Cup", "country": "Angola"},
    1193: {"name": "Super Cup", "country": "Kenya"},
    1194: {"name": "Super Cup", "country": "Tunisia"},
    1195: {"name": "Liga E Pare", "country": "Kosovo"},
    1196: {"name": "Division One League", "country": "Ghana"},
    1197: {"name": "FA Cup", "country": "Oman"},
    1198: {"name": "Serie A Cup Women", "country": "Italy"},
    1199: {"name": "League Cup", "country": "Hong-Kong"},
    1200: {"name": "Liga MX U21", "country": "Mexico"},
    1201: {"name": "IFA Shield", "country": "India"},
    1202: {"name": "Australian Championship", "country": "Australia"},
    1203: {"name": "Piauiense - 2", "country": "Brazil"},
    1204: {"name": "Rondoniense - 2", "country": "Brazil"},
    1205: {"name": "Kings Cup", "country": "Brazil"},
    1206: {"name": "CONMEBOL Nations League Women", "country": "World"},
    1207: {"name": "CONCACAF Series", "country": "World"},
    1208: {"name": "Arabian Gulf Cup U23", "country": "World"},
    1209: {"name": "Guangdong - Hong Kong Cup", "country": "Hong-Kong"},
    1210: {"name": "Super Cup", "country": "Greece"},
    1211: {"name": "Tipsport Liga", "country": "Czech-Republic"},
    1212: {"name": "Copa De La Liga Auf", "country": "Uruguay"},
    1213: {"name": "Kings World Cup Nations", "country": "World"},
    1214: {"name": "OFC Pro League", "country": "World"},
    1215: {"name": "Obos Supercup", "country": "Norway"},
    1216: {"name": "Serie Rio De La Plata", "country": "World"},
    1217: {"name": "FIFA Women Champions Cup", "country": "World"},
    1218: {"name": "Pro League U23", "country": "United-Arab-Emirates"},
    1219: {"name": "Copa Presidente", "country": "El-Salvador"},
    1220: {"name": "Copa De La Liga", "country": "Chile"},
    1221: {"name": "Super Cup", "country": "Bosnia"},
    1222: {"name": "FIFA Series", "country": "World"},
    1223: {"name": "Copa Norte", "country": "Brazil"},
    1224: {"name": "Copa Sul-Sudeste", "country": "Brazil"},
    1225: {"name": "Copa Centro-Oeste", "country": "Brazil"},
}

# Total leagues: 1225